feat: Loggerの作成を行う関数を追加
nitkgsm-dev/labot pull request #5
Opened 2024-02-12 13:59 UTC by aqyuki

ロガーを作成するための統一的なインターフェイスとして、`loggin`パッケージを追加し、その中にBuilderを定義しました。

2024-02-12 14:12 UTC, ikafly144 commented on pkg/logging/builder.go
> +func (b Builder) Build() *slog.Logger {
```suggestion
func (b *Builder) SetLevel(level LogLevel) *Builder {
	b.level = level
	return &b
}

func (b *Builder) SetDateFormat(format string) *Builder {
	b.dateFormat = format
	return &b
}

func (b *Builder) SetLogFormat(format logFormat) *Builder {
	b.logFormat = format
	return &b
}

func (b *Builder) SetDisplaySource(display bool) *Builder {
	b.displaySource = display
	return &b
}

func (b *Builder) SetWriter(writer io.Writer) *Builder {
	b.writer = writer
	return &b
}

func (b *Builder) Build() *slog.Logger {
```

2024-02-12 14:12 UTC, ikafly144 requested changes
Builderはポインタメソッドを使ってほしい

2024-02-13 03:38 UTC, ikafly144 requested changes
if文の中で代入されたJSONHandlerが上書きされて使われていないですね

2024-02-13 03:38 UTC, ikafly144 commented on pkg/logging/builder.go
> +	return slog.New(handler)
JSONHandlerが代入されたあと使われてないです

2024-02-13 03:38 UTC, aqyuki commented on pkg/logging/builder.go
> +	return slog.New(handler)
あ　まじだ

2024-02-13 05:47 UTC, ikafly144 requested changes
FormatTextとFormatJSON、値一緒じゃね

2024-02-13 05:47 UTC, ikafly144 commented on pkg/logging/builder.go
> +)
```suggestion
const (
	FormatText logFormat = iota
	FormatJSON
)
```

2024-02-13 06:01 UTC, ikafly144 approved these changes
LGTM!

2024-02-13 06:01 UTC, merged