feat: コマンドラインインターフェースを改善する
nitkgsm-dev/labot pull request #7
Opened 2024-02-13 07:33 UTC by ikafly144

- ロギングに`logging`パッケージを使う
- トークンとロギングの設定を`flags`で行うようにする
- コンソールコマンドの履歴を`.console_history`に保存するようにする
- readyを受け取るまで待つようにする
- `ping` `guild list`コンソールコマンドを追加する

2024-02-13 07:51 UTC, aqyuki requested changes

2024-02-13 07:51 UTC, aqyuki commented on main.go
> +
```suggestion
var (
	jsonLog    = flag.Bool("json-log", false, "enable json log format")
	token      = flag.String("token", "", "discord bot token")
	debug      = flag.Bool("debug", false, "enable debug mode")
	dateFormat = flag.String("date-format", time.TimeOnly, "date format")
)

func init() {
	flag.Parse()
}
```

バラバラに初期化するよりもこっちのほうが、いいと思う。

2024-02-13 07:51 UTC, aqyuki commented on main.go
>  		panic(err)
panicで落とすよりも、slog.Errorをつかって、エラー内容とかを出力してほしい
ほかの、場所もpanicを使うよりはエラー内容を出力した後にos.Exit()とかで落としたほうがいいと思う

2024-02-13 07:51 UTC, aqyuki commented on go.mod
> +replace github.com/disgoorg/disgo v0.17.1 => github.com/nitkgsm-dev/disgo v0.0.0-20240213053746-781cf79a7b66
**Out of Scope**
このPRで対応しなくてもいいんですけど、replaceを使うよりも`github.com/nitkgsm-dev/disgo`を指定したほうがいい。

2024-02-13 08:00 UTC, ikafly144 commented on go.mod
> +replace github.com/disgoorg/disgo v0.17.1 => github.com/nitkgsm-dev/disgo v0.0.0-20240213053746-781cf79a7b66
github.com/nitkgsm-dev/disgoを直接importするにはgithub.com/nitkgsm-dev/disgo側のモジュール名を書き換えなきゃいけないのでreplaceのままでいいと思う

2024-02-13 08:03 UTC, aqyuki commented on go.mod
> +replace github.com/disgoorg/disgo v0.17.1 => github.com/nitkgsm-dev/disgo v0.0.0-20240213053746-781cf79a7b66
あね、そういう事情あるなら修正しなくていいよ。

2024-02-13 08:16 UTC, ikafly144 commented on main.go
>  		panic(err)
slog.Errorで出力するのは賛成だけど、panicじゃないとdeferした`client.Close()`が実行されないからos.Exitで落とすよりpanicのほうがいいと思う
ゲートウェイが開けていてReadyを受け取れない状況（例えば特権インテントをボットに付与してないとき）だと`client.Close()`を呼び出すとデッドロックするからos.Exitで落としてる

2024-02-13 08:27 UTC, aqyuki commented on main.go
>  		panic(err)
deferはos.Exitだと動かないのか…　とりあえず、今回はerrorのロギング処理をするようにしてくれれば大丈夫です。

ただ、panicは開発時に気づくべき致命的なバグを含んでるときにだけ使いたいっておもってるのでいずれ変更したいとは思う。

2024-02-13 08:43 UTC, ikafly144 commented on main.go
>  		panic(err)
panicを使わずdeferを呼び出して異常終了する方法としてこんなのが思いつくけどこのPRで対応していいかな

```go

// start()を呼び出してエラーが帰ってきたらslog.Errorでロギングしてos.Exitする
func main() {
	if err := start(); err != nil {
		slog.Error("an error occurred", slog.Any("err", err))
		os.Exit(1)
	}
}

// 既存のmain()の中身
func start() error {
	return nil
}
```

2024-02-13 08:47 UTC, aqyuki commented on main.go
>  		panic(err)
実装方法はそれで良いと思うけど、このPRでは対応しなくても良いよ
また別のPRで立ててくれれば

2024-02-14 11:20 UTC, aqyuki approved these changes
LGTM

2024-02-14 11:20 UTC, merged