refactor: main関数を内部関数に移動させる
nitkgsm-dev/labot pull request #9
Opened 2024-02-19 11:39 UTC by ikafly144

エラーの際にpanicで落とすのではなくerrorを返してos.Exitで落とすようにする

2024-02-19 11:53 UTC, aqyuki requested changes

2024-02-19 11:53 UTC, aqyuki commented on main.go
> +	}
exitCodeみたいな型を定義する方法の方がいいがする

```suggestion
  type exitCode int
  
  const (
    statusOK exitCode = 0
    statusError       = 1
  )
  os.Exit(int(realMain()))
```

2024-02-19 11:53 UTC, aqyuki commented on main.go
> +		return err
exitCodeを返すようにすればいい

2024-02-22 08:48 UTC, ikafly144 commented on main.go
> +	}
なるべくGoのerrorで扱いたいからこんな風に扱うのはどうかな
```suggestion
type ExitError struct {
	err error
	exitCode int
}

cosnt (
	statusOK = iota
	statusError
)

func realMain() *ExitError {
```

2024-02-23 02:59 UTC, aqyuki commented on main.go
> +	}
Goのエラー型で扱いたいならexitCodeのフィールドはいらないかな
```go
type ExitError truct {
   err error
}
```
こんな感じで，エラー起きたときはerrorを返すっていういつもの感じで実装してもらえれば．
ただ，エラーが発生したことを，main関数に伝える必要が今の実装だと必要ないからその場合エラー発生時のloggingをmain関数に移すとかしたほうがいいかもしれない

2024-02-24 06:56 UTC, aqyuki approved these changes

2024-02-24 06:56 UTC, merged